services:
  - type: web
    name: tile-bot-app
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ollama serve
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: OLLAMA_MODELS
        value: llava
    ports:
      - 11434
